### ISSUE TITLE
EDA:

### ISSUE THREAD

**Issue by malgorzata-szczypior** [infoshareacademy/jdszr3-datavirus#11]
- zapoznanie z danymi
- podstawowa statystyka
-zliczenie wierszy dla poszczegolnych kolumn
-zliczenie wierszy dla wybranych kolumn z podziałem na płeć
-dodanie kolumny wiek - lw atach

**Comment by dbromirska** [comment]
- zapoznanie się z danymi
- podstawowe statystyki
- dodanie kolumny bmi oraz wiek w latach
- czyszczenie danych - wzrost, waga, cisnienie skurczowe i rozkurczowe, bmi
